<?xml version="1.0"?>
<robot name="robot_loc_nav" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Constants for the robot-->
    <xacro:property name="width" value="0.4"/>
    <xacro:property name="depth" value="0.3"/>
    <xacro:property name="height" value="0.2"/>
    <xacro:property name="radius" value="0.1"/>
    <xacro:property name="length" value="0.04"/>
    <xacro:property name="radius2" value="0.05"/>
    <xacro:property name="mass" value="1"/>
    <xacro:property name="rotation" value="3.14"/>

    <!-- Import colors for Robot-->
    <xacro:include filename="$(find robot_loc_nav)/urdf/materials.xacro"/>

    <!--Import Gazebo plugins. Colors and Differetnial Drive-->
    <xacro:include filename="$(find robot_loc_nav)/urdf/my_robot.gazebo"/>

    <!-- Import Gazebo plugin for LASER-->
    <xacro:include filename="$(find robot_loc_nav)/urdf/laser.gazebo"/>

    <!-- Import Gazebo plugin for IMU-->
    <xacro:include filename="$(find robot_loc_nav)/urdf/imu.gazebo"/>

    <!-- Import Gazebo plugins for depth camera-->
    <!--<xacro:include filename="$(find robot_loc_nav)/urdf/depth_camera.gazebo"/>-->


    <!-- Default inertia for boxes-->
    <xacro:macro name="default_inertia_boxes" params="mass width depth height">
        <inertial>
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia ixx="${(mass/12)*(height*height+depth*depth)}" ixy="0" ixz="0"
                     iyy="${(mass/12)*(width*width+depth*depth)}" iyz="0"
                     izz="${(mass/12)*(height*height+width*width)}"/>
            </inertial>
    </xacro:macro>
    
    <!-- Default inertia for cylinders-->
    <xacro:macro name="default_inertia_cylinder" params="mass radius length">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass/2}"/>
            <inertia ixx="${(mass/12)*(3*radius*radius+length*length)}" ixy="0" ixz="0"
                     iyy="${(mass/12)*(3*radius*radius+length*length)}" iyz="0" 
                     izz="${(mass/2)*radius*radius}"/>
        </inertial>
    </xacro:macro>

    <!-- Base Link-->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${depth} ${height}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${depth} ${height}"/>
            </geometry>
        </collision>
        <xacro:default_inertia_boxes mass="${mass/2}" height="${height}" width="${width}" depth="${depth}"/>
    </link>

    <!-- Robot Footprint -->
    <link name="base_footprint">
        <xacro:default_inertia_boxes mass="0" width="0" depth="0" height="0"/>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(radius+0.05)}" rpy="0 0 0"/>
    </joint>   
    
    <!-- Caster Link-->
    <link name="caster">
        <visual>   
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${radius2}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${radius2}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass/10}"/>
            <inertia ixx="${(2/5)*(mass/10)*radius2*radius2}" ixy="0" ixz="0"
                     iyy="${(2/5)*(mass/10)*radius2*radius2}" iyz="0"
                     izz="${(2/5)*(mass/10)*radius2*radius2}"/>
        </inertial>
    </link>

    <!-- Joint for Caster. The parent will be the base_link-->
    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster"/>
        <origin xyz="${width/2-radius2} 0 -0.1"/>
    </joint>

    <!-- Create a xacro macro which defines all the necessaries for the wheels -->
    <xacro:macro name="wheel" params="prefix y_reflect">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${rotation/2} 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="Gray">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${rotation/2} 0 0"/> 
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>

            <xacro:default_inertia_cylinder mass="0.5" radius="${radius}" length="${length}"/>
        </link>
        <!-- Joint for wheels-->
        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${-width/2} ${y_reflect*(length/2+depth/2)} ${-radius/2}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <!-- We define the two wheels-->
    <xacro:wheel prefix="left" y_reflect="1" />
    <xacro:wheel prefix="right" y_reflect="-1" />

    <!--LINK LASER-->
    <link name="hokuyo">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find robot_loc_nav)/meshes/hokuyo.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005" />
        </inertial>
    </link> 
    
    <!--JOINT FOR LASER -->
    <joint name="joint_laser" type="fixed">
        <parent link="base_link"/>
        <child link="hokuyo"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${width/2-0.05} 0 ${height/2+0.025}" rpy="0 0 0"/>
    </joint>
    
    <!-- imu link-->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
        <xacro:default_inertia_boxes mass="0.1" width="0.1" depth="0.1" height="0.1"/>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0.01"/>
    </joint>

    <!-- Camera Link-->
    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.130 0.022"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.130 0.022"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.035"/>
            <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.215 0 0.05" rpy="0 0 0"/>
    </joint>

    <link name="camera_depth_frame"/>

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame"/>
    </joint>
    
</robot>